name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  notify_discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Discord notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "New release: ${{ github.event.release.tag_name }}\nDescrtiption: ${{ github.event.release.body }}\nClick here for more info: ${{ github.event.release.html_url }}"}' \
            https://discord.com/api/webhooks/1200776192299638954/PkVpj2ckfqaV93f1A2WOwEKK_LbkAI8o_7gES5ijFFJ6I_qgI6DI1w_c2luFuAuKSYy1
        env:
          YOUR_DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1200776192299638954/PkVpj2ckfqaV93f1A2WOwEKK_LbkAI8o_7gES5ijFFJ6I_qgI6DI1w_c2luFuAuKSYy1
